print("hello world")
print("what is your name?")
myname = input()
print("it is goood t  meet you" + myname)
print("lengtbh your name is:")
print(len(myname))
print("what is  your age?")
myage = input()
print("you will be "    +    str(int(myage) + 1)     +      "in year ")
